name: Build Windows Executable

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    # Use bash instead of PowerShell to avoid random failures
    # Reference: https://github.com/orgs/community/discussions/26933
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build executable
      run: |
        pyinstaller --clean --noconfirm --onefile --windowed --name MCP_Client_X app_gui.py \
          --hidden-import=uvicorn \
          --hidden-import=click \
          --hidden-import=starlette \
          --hidden-import=fastapi \
          --hidden-import=httpx \
          --hidden-import=ollama \
          --hidden-import=mcp \
          --add-data "src;src"
        
    - name: Test executable
      run: |
        if [ -f "dist/MCP_Client_X.exe" ]; then
          echo "✅ Executable built successfully"
          size=$(stat -c%s "dist/MCP_Client_X.exe")
          size_mb=$((size / 1024 / 1024))
          echo "📦 Size: ${size_mb} MB"
        else
          echo "❌ Executable not found"
          exit 1
        fi
        
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: MCP_Client_X_Windows
        path: dist/MCP_Client_X.exe
        retention-days: 30
        
    - name: Create installer (if Inno Setup available)
      run: |
        # Check if Inno Setup is available
        if command -v iscc.exe &> /dev/null; then
          echo "📦 Creating installer with Inno Setup..."
          iscc.exe installer.iss
          if [ -f "dist_installer/MCP_Client_X_Setup.exe" ]; then
            echo "✅ Installer created successfully"
          fi
        else
          echo "⚠️ Inno Setup not found, skipping installer creation"
        fi
        
    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      if: success() && hashFiles('dist_installer/MCP_Client_X_Setup.exe') != ''
      with:
        name: MCP_Client_X_Installer
        path: dist_installer/MCP_Client_X_Setup.exe
        retention-days: 30
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/MCP_Client_X.exe
          dist_installer/MCP_Client_X_Setup.exe
        body: |
          ## MCP Client X Release
          
          ### 🚀 Quick Start
          1. Download `MCP_Client_X_Setup.exe` for full installation
          2. Or download `MCP_Client_X.exe` for portable version
          3. Make sure Ollama is installed and running
          4. Run `ollama pull qwen3:8b` to get the AI model
          
          ### 📋 Requirements
          - Windows 10/11 (64-bit)
          - Ollama installed and running
          - qwen3:8b model downloaded
          
          ### 🔗 Links
          - [Windows README](README_WINDOWS.md)
          - [Ollama Download](https://ollama.ai/download/windows)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 